
# Bacnet server YAML configuration file

server_name: My Bacnet Server
device_id: 2508
iface: eth0
port: 47808

bi_max: 10
bo_max: 10
bv_max: 20
ai_max: 10
ao_max: 10
av_max: 20

mqtt:
  broker_ip: 127.0.0.1
  broker_port: 1883
  debug: false
  enable: true
  write_via_subscribe: true
  retry_enable: true
  retry_limit: 5
  retry_interval: 10

objects:
  - ai
  - ao
  - av
  - bi
  - bo
  - bv

properties:
  - name
  - pv
  - pri

bacnet_client:
  debug: true
  enable: true
  commands:
    - whois
    - read_value
    - write_value
